#José Astorga

######################################      ######################################
# Al parecer no se puede usar agregaciones por lo que resuelvo limitando en 1
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX imdb: <http://imdb.com/rdf/>
SELECT ?top ?nombre 
WHERE { ?actor a foaf:Person .
        ?actor foaf:name ?nombre .
        ?actor imdb:countTop250 ?top 
    }
ORDER BY DESC (?top)
LIMIT 1
	
######################################      ######################################
